import {
    createDefaultModule,
    createDefaultSharedModule,
    type DefaultSharedModuleContext,
    inject,
    type LangiumServices,
    type LangiumSharedServices,
    type Module,
    type PartialLangiumServices,
} from "langium";

import { JSPLFormatGeneratedModule, JSPLGeneratedSharedModule } from "./generated/module";
import { JSPLFormatValidator, registerValidationChecks } from "./jspl-validator";
import { JSPLValueConverter } from "./jspl-converter";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type JSPLFormatAddedServices = {
    validation: {
        JSPLFormatValidator: JSPLFormatValidator;
    };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type JSPLFormatServices =
    & LangiumServices
    & JSPLFormatAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const JSPLFormatModule: Module<
    JSPLFormatServices,
    PartialLangiumServices & JSPLFormatAddedServices
> = {
    validation: {
        JSPLFormatValidator: () => new JSPLFormatValidator(),
    },
    parser: {
        ValueConverter: () => new JSPLValueConverter(),
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createJSPLFormatServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    JSPLFormat: JSPLFormatServices;
}
{
    const shared = inject(
        createDefaultSharedModule(context),
        JSPLGeneratedSharedModule,
    );

    const JSPLFormat = inject(
        createDefaultModule({ shared }),
        JSPLFormatGeneratedModule,
        JSPLFormatModule,
    );

    shared.ServiceRegistry.register(JSPLFormat);
    registerValidationChecks(JSPLFormat);

    return { shared, JSPLFormat };
}
